<a href="https://colab.research.google.com/github/oceam/agri-image/blob/main/codes/Googlecolab_fundamentals_2_JP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Googlecolab_fundamentals_2

**Basic syntax**
Run following cell first.   



In [ ]:
x = pi
print(x)

NameError: ignored

Why it happens?
Because python will need to import **module** by yourself.  
You can import whole module or just what you need (same as R).  
Typically, importing just the whole module will get you what you need.  There are actually a few ways to import functionality from modules. One of the most common is to simply import the whole Python module. To do that, you just follow the import command with the name of the Python module you want to import. For example, this imports the entire math module, which has lots of functions and stuff for doing math:  
なぜか$\pi$が定義されていなかったようでした。その理由は、
Pythonは自分で**モジュール**をインポートする必要があるからです。 
モジュール全体をインポートすることもできますし、必要なものだけをインポートすることもできます（Rと同じです）。 
一般的には、モジュール全体をインポートすれば、必要なものが手に入ります。 モジュールから機能をインポートするには、実はいくつかの方法があります。最も一般的なのは、単純にPythonモジュール全体をインポートする方法です。これを行うには、importコマンドに続けてインポートしたいPythonモジュールの名前を指定するだけです。例えば、これはmathモジュール全体をインポートしており、そこには数学を行うための関数やものがたくさんあります。

In [ ]:
import math

After you import a Python module, the ```dir()``` and ```help()``` functions work on that too. For example, if you tried doing dir(math) or help(math) before import math, you'd get an error. That’s because that math package isn’t part of the standard library. However, if you do import math first, and then ```help(math)```, then it all works.  
Python モジュールをインポートした後、```dir()``` と ```help()``` 関数はそのモジュールに対しても機能します。例えば、```import math``` の前に ```dir(math)``` や ```help(math)``` を実行しようとすると、エラーが発生します。これは、その数学パッケージが標準ライブラリの一部でないためです。

In [ ]:
dir(math)

['__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'ceil',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'e',
 'erf',
 'erfc',
 'exp',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'pi',
 'pow',
 'radians',
 'remainder',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc']

Yes, pi is there! Now let's see:

In [ ]:
x =pi
print(x)

NameError: ignored

In [ ]:
y = sin(-5)
print(y)

0.9589242746631385


$\pi$ isn’t part of the standard library that’s always available to your Python code. To use it, you have to import the math module. There are 3 ways to do that:  
1. To precede the part you want to use with the name of the module and a dot like `math.pi`.
2. To import the module by associate the name of everything in the math module with that Python module a Python module like `from math import *`.
3. To import just what you need (pi) using a syntax like `from math import pi
`.    

$pi$ は、Pythonコードで常に利用できる標準ライブラリの一部ではありません。それを使用するには、mathモジュールからインポートする必要があります。その方法は3つあります。 
1. 使用したい部分の前にモジュール名と `math.pi` のようなドットを置く。
2. 「from math import *`」のように、mathモジュール内のすべての名前をそのPythonモジュールに関連付けることでモジュールをインポートする方法。
3. 必要なものだけをインポートするには、 `from math import pi` のような構文にします。

In [ ]:
x =math.pi
print(x)

3.141592653589793


In [ ]:
from math import *
x =pi
print(x)

3.141592653589793


In [ ]:
from math import pi
x =pi
print(x)

3.141592653589793


In [ ]:
y = sin(-5)
print(y)

0.9589242746631385


Using format() method to change the positional argument  
format() メソッドを使用して位置の引数を変更する

In [ ]:
print('{:.20f}'.format(x))
print('{:.4f}'.format(x))

3.14159265358979311600
3.1416


In [ ]:
x2='{:.10f}'.format(x)
x2

'3.1415926536'

# **Array types**
# **配列**

In [2]:
import numpy as np
a = 4
print("a is:",a,'\n')
a = np.array([3, 5], dtype=np.int64)
print("a is:\n", a)
print("shape of a is: {}".format(a.shape))
print("size of a is:{}".format(a.size),'\n')
a = np.array(([1], [3]), dtype=np.int64)
print("a is:\n", a)
print("shape of a is: {}".format(a.shape))
print("size of a is:{}".format(a.size),'\n')
a = np.array(([3,4,5], [6,7,8]), dtype=np.int64)
print("a is:\n", a)
print("shape of a is: {}".format(a.shape))
print("size of a is:{}".format(a.size),'\n')
#[3 5]
#[1;3]
#[3 4 5; 6 7 8]

a is: 4 

a is:
 [3 5]
shape of a is: (2,)
size of a is:2 

a is:
 [[1]
 [3]]
shape of a is: (2, 1)
size of a is:2 

a is:
 [[3 4 5]
 [6 7 8]]
shape of a is: (2, 3)
size of a is:6 



**Evenly-spaced vectors**  
Use np.linspace() when the exact values for the start and end points of your range are the important attributes in your application.  
Use np.arange() when the step size between values is more important.  
**等間隔のベクトル**  
範囲の始点と終点の間の数を定義するならnp.linspace()  
範囲の始点と終点の間ののステップサイズを定義するならnp.arange()


In [10]:
b= np.arange(1,5)
print("use arrange:{}".format(b),'\n')
b= np.arange(1,5,0.5)
print("use arrange:{}".format(b),'\n')
b= np.linspace(1, 10, num=5)
print("use linspace:{}".format(b),'\n')
b= np.random.rand(5)
print("generate random number:{}".format(b),'\n')
b= np.zeros((2))
print("generate zero vector:{}".format(b),'\n')
b= np.ones((2))
print("generate one vector:{}".format(b),'\n')

use arrange:[1 2 3 4] 

use arrange:[1.  1.5 2.  2.5 3.  3.5 4.  4.5] 

use linspace:[ 1.    3.25  5.5   7.75 10.  ] 

generate random number:[0.40159976 0.25032458 0.7283896  0.82415405 0.15440458] 

generate zero vector:[0. 0.] 

generate one vector:[1. 1.] 



**Creating matrices**  
Create a square matrix with x rows and x columns.  
**行列の作成**  
x行x列の正方行列を作成します。


In [12]:
c= np.random.rand(2,2)
print("generate random number matric:{}".format(c),'\n')
c= np.zeros((3,3))
print("generate zero matric:{}".format(c),'\n')
c= np.ones((4,4))
print("generate one matric:{}".format(c),'\n')


generate random number matric:[[0.53796033 0.2777728 ]
 [0.46584775 0.42640695]] 

generate zero matric:[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

generate one matric:[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 



**Indexing**  


In [13]:
A = np.array(([3,4],[5,6],[7,8]), dtype=np.int64)
print(A,'\n')

[[3 4]
 [5 6]
 [7 8]] 



Access the element in the second column of the last row.
Please pay attention of the **index numbers** here.



In [14]:
print(A[2,1],'\n')

8 



Access the entire second row.


In [15]:
print(A[1,:],'\n')

[5 6] 



Access all columns of the first three rows.


In [16]:
print(A[0:3,:],'\n')

[[3 4]
 [5 6]
 [7 8]] 



Change the value of the second element an array to 11.

In [17]:
A[1,0]=11
print(A,'\n')

[[ 3  4]
 [11  6]
 [ 7  8]] 



**Array operations**


Matrix operations follow the rules of linear algebra and are not compatible with multidimensional arrays. The required size and shape of the inputs in relation to one another depends on the operation. For nonscalar inputs, the matrix operators generally calculate different answers than their array operator counterparts.

For example, if you use the matrix right division operator, /, to divide two matrices, the matrices must have the same number of columns. But if you use the matrix multiplication operator, *, to multiply two matrices, then the matrices must have a common inner dimension. That is, the number of columns in the first input must be equal to the number of rows in the second input. The matrix multiplication operator calculates the product of two matrices with the formula  
$C(i,j) = \sum\limits_{k=1}^{n}A(i,k)B(k,j)$  
<!-- $C(i,j) = \sum^{n}_{k=1}A(i,k)B(k,j)$ -->

In [ ]:
a_1=np.array(([1,1],[1,1]), dtype=np.int64)
b_1=np.array(([2,2],[2,2]), dtype=np.int64)

Perform matrix multiplication.


In [ ]:
print(np.matmul(a_1,b_1))


Perform element-wise multiplication.


In [ ]:
print(np.multiply(a_1,b_1))


**Multiple outputs**


Save the number of rows and columns in A to two different variables.


In [ ]:
print(A,'\n')
Arow, Acol = A.shape
print(Arow,Acol, '\n')

Calculate the maximum value of A and its corresponding index value.  
note: start from version 1.22.0.  
np.argmax will support numpy.argmax(a, axis=None, out=None, *, keepdims=<no value>)

In [ ]:
print(A,'\n')
AMax_1 = np.max(A)
print('AMax_1 is\n',AMax_1, '\n')
idx_1 = np.argmax(A)
print('idx_1 is\n',idx_1, '\n')

AMax_2=np.max(A,axis=0, keepdims=True)
print('AMax_2 is\n', AMax_2, '\n')
idx_2 = np.argmax(A, axis=0)
print('idx_2 is\n',idx_2, '\n')

AMax_3=np.max(A,axis=1, keepdims=True)
print('AMax_3 is\n', AMax_3, '\n')
idx_3 = np.argmax(A, axis=1)
print('idx_3 is\n',idx_3, '\n')


**Plotting**


In [ ]:
# x = np.random.rand(5,1)
# y = np.random.rand(5,1)
# z = np.random.randi(5,1)
# z = np.random.randint(1, 5, (5, 1))
x = np.array(([1],[2],[2],[1],[1]))
y = np.array(([1],[1],[2],[2],[1]))
z = np.array(([5],[2],[5],[2],[5]))

Plot a red (r) dashed (--) line with a circle (o) marker, with a heavy line width.

In [ ]:
import matplotlib.pyplot as plt
plt.plot(x, y, color="r",ls="-",marker="o",linewidth=3)
# Add the next line to existing plot.
plt.plot(x, z, color="g",ls="-",marker="*",linewidth=1)
plt.show()

Create a new axes for the next plotted line.


In [ ]:
plt.plot(x, z, color="g",ls="-",marker="o",linewidth=3)
#Add a label to a plot.
plt.title("green plot of xz")
plt.show()



**Using tables**

In [ ]:
import pandas as pd
import numpy as np
HeightYards = np.random.rand(5,1)
data = pd.DataFrame(HeightYards)
data.columns = ["HeightYards"]
data

Extract the variable HeightYards from the table data.

In [ ]:
data.HeightYards

Derive a table variable from existing data.


In [ ]:
data['HeightMeters'] = pd.DataFrame(data.HeightYards*0.9144)
data

**Logicals**


Compare a vector to the value 12.

In [ ]:
np.array(([5,10,15]))>12

Extract all elements in v1 that are greater than 6.


In [ ]:
v1 = np.array(([5,10,15]))
idx= np.where(v1 > 6)
v1[idx]


Replace all values in x that are equal to 999 with the value 1.

In [ ]:
x = np.array(([1,3,999,2]))
print('Original x is\n', x, '\n')
idx= np.where(x == 999)
x[idx]=1
print('Replaced x is\n', x, '\n')


**Programming**


In [ ]:
import pandas as pd
import numpy as np
x = np.random.rand(1)
print(x)

If x is greater than 0.5, set the value of y to 3. Otherwise, set the value of y to 4.

In [ ]:
 if x>0.5:
    y=3
 else:
    y=4
    print(y)

The loop counter (c) progresses through the values 1:3 (1, 2, and 3). The loop body displays each value of c.


In [ ]:
for c in range(3):
    print(c)

In [ ]:
for c in range(1,4):
    print(c)